name = "aonyx_graph"
version = "1.0.3"
gleam = ">= 1.10.0"

description = "A graph library. Including path finding."
licences = ["MIT"]
repository = { type = "github", user = "aonyxrocks", repo = "aonyx_graph" }


[dependencies]
gleam_stdlib = ">= 0.59.0 and < 2.0.0"

[dev-dependencies]
gleeunit = ">= 1.0.0 and < 2.0.0"
